# Generated by Django 5.2.17 on 2026-08-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_printify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_product_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
