# Generated by Django 5.2.17 on 2026-08-31 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_external_image_url_product_is_printify_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintifyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printify_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Printify Product',
                'verbose_name_plural': 'Printify Products',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'My Product', 'verbose_name_plural': 'My Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='external_image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_printify',
        ),
        migrations.RemoveField(
            model_name='product',
            name='printify_product_id',
        ),
        migrations.CreateModel(
            name='PrintifyProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printify_url', models.URLField(blank=True)),
                ('custom_image', models.ImageField(blank=True, null=True, upload_to='printify_products/')),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.printifyproduct')),
            ],
            options={
                'verbose_name': 'Printify Product Image',
                'verbose_name_plural': 'Printify Product Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrintifyVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printify_variant_id', models.PositiveBigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('production_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.printifyproduct')),
            ],
            options={
                'verbose_name': 'Printify Variant',
                'verbose_name_plural': 'Printify Variants',
                'ordering': ['id'],
            },
        ),
    ]
