# Generated by Django 5.2.17 on 2026-08-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_printifyproduct_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
