# Generated by Django 5.2.17 on 2026-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_printify_fulfillment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAccessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=True, verbose_name='Private shop enabled')),
                ('access_password', models.CharField(blank=True, default='', help_text='Visitors must enter this password while private shop mode is enabled.', max_length=255, verbose_name='Access password')),
            ],
            options={
                'verbose_name': 'Site Access',
                'verbose_name_plural': 'Site Access',
            },
        ),
    ]
